### ISSUE TITLE
Smart fee calculation

### ISSUE THREAD

**Issue by NCrashed** [hexresearch/ergvein#368]
We need to select fee level for outcoming transactions. At least we need three options:
* Fastest but expensive (confirm in next 2 blocks)
* Moderate (confirm in 2-10 blocks)
* Cheapest but slow (confirm in 10+ blocks)

Research if we can do this without introducing dependency on external prediction service (such as https://bitcoinfees.earn.com/api) by tracking mempool from #367.

**Comment by LeMarwin** [comment]
## Research

After researching, by far the easiest way is to delegate this task to indexers. Reasons:

* Bitcoin Core already has an implementation, accessible via an RPC call 
* Indexers are already connected to their node via RPC 
* Fee estimation is not a private information nor can it be used to identify users
* Indexers can keep track of aforementioned three options and the user can collect info from multiple indexers to average out 
* We can always add an option to enter the fee manually, so that especially paranoid users have full control if they wish

## Outline 

`bitcoin-api` package does not implement a call to `estimatesmartfee` method and does not expose `Network.Bitcoin.Api.Internal` with its `call` function

Thus we need to fork `bitcoin-api` and add an `estimatesmartfee` call.

Keep track of three (or more) options by calling `estimatesmartfee` after each new block

Add indexer API to poll fees estimation.

Use fees estimate from indexers and `guessTxFee` function from `Network.Haskoin.Transaction.Builder` to display the final fee estimate for the specific transaction the user wants to make.

**Comment by LeMarwin** [comment]
Closed by 3f621ce3d2ba48ec79c4a05a0df5a227d0747d7f
